### ISSUE TITLE
Wish: support  Grandfather-Father-Son expiration algorithm.

### ISSUE THREAD

**Issue by markstos** [tangerinedream/SnapshotExpirationUtility#2]
The [grandfatherson](https://github.com/ecometrica/grandfatherson) project has implemented a popular backup retention algorithm in Python, including lots of test coverage. 

It looks like it would be easy to plug in here, allowing users to specify rules like "keep 1 per week for the last 3 weeks" and "keep 1 per month for the last 8 months".

**Comment by markstos** [comment]
I could possibly help implement this if it's of interest to you. Let me know.

**Comment by tangerinedream** [comment]
Sure, I would be happy to review an implementation. Please let me know when you've something to share.

**Comment by tangerinedream** [comment]
This feature has been implemented.  Works great and provides much more flexibility, in terms of supporting custom retention periods.
